
[package]
name = "secure_transfer"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8"
ctr = "0.9"
rsa = { version = "0.9", features = ["pem"] }
rand = "0.8"
sha2 = "0.10"
xxhash-rust = { version = "0.8", features = ["xxh64"] }

serde = { version = "1", features = ["derive"] }
bincode = "1.3"

crossbeam = "0.8"

anyhow = "1"

parking_lot = "0.12"

bytes = "1"
pem = "3"
crossbeam-channel = "0.5"
socket2 = "0.5"
memmap2 = "0.9"


num_cpus = "1.16"
crossbeam-queue = "0.3"
